name: skeleton-landophp
services:
  skeletonappserver:
    type: php:7.4
    xdebug: true
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=skeletonappserver"
    build:
      - composer install